### ISSUE TITLE
Build error gcc (GCC) 6.1.1 20160501

### ISSUE THREAD

**Issue by heshamsafi** [xtaci/algorithms#46]
Hello,

first of all, this is a great compilation of non-trivial algorithms ... thank you for putting it together.

secondly, I get this build error for suffix_tree in my environment.
most probably compiler dependent issues.
I will look into it and if i fix it I will send a pull request from a fork.

In file included from src/suffix_tree_demo.cpp:1:0:
./include/suffix_tree.h: In member function ‘Iterator SuffixTree::inc_search(Iterator)’:
./include/suffix_tree.h:34:41: warning: typedef ‘T’ locally defined but not used [-Wunused-local-typedefs]
   typedef typename Iterator::value_type T; // extract real type
                                         ^
./include/suffix_tree.h: In function ‘std::ostream& operator<<(std::ostream&, SuffixTree::Node&)’:
./include/suffix_tree.h:214:8: error: ‘typedef struct SuffixTree::Edge SuffixTree::Edge’ is private within this context
    map<Edge*, bool>::iterator iter;
        ^~~~
./include/suffix_tree.h:149:22: note: declared private here
  typedef struct Edge Edge;
                      ^~~~
./include/suffix_tree.h:215:14: error: ‘typedef struct SuffixTree::Edge SuffixTree::Edge’ is private within this context
    map<char, Edge*>::iterator iter_f;
              ^~~~
./include/suffix_tree.h:149:22: note: declared private here
  typedef struct Edge Edge;
                      ^~~~
src/suffix_tree_demo.cpp: At global scope:
src/suffix_tree_demo.cpp:107:70: error: no ‘SuffixTree::Node* SuffixTree::seperate_edge(SuffixTree::Node*, SuffixTree::Edge*)’ member function declared in class ‘SuffixTree’
 SuffixTree::Node* SuffixTree::seperate_edge(Node * node, Edge* a_edge)
                                                                      ^
src/suffix_tree_demo.cpp:107:13: error: ‘typedef struct SuffixTree::Node SuffixTree::Node’ is private within this context
 SuffixTree::Node* SuffixTree::seperate_edge(Node * node, Edge* a_edge)
             ^~~~
In file included from src/suffix_tree_demo.cpp:1:0:
./include/suffix_tree.h:81:22: note: declared private here
  typedef struct Node Node;
                      ^~~~
src/suffix_tree_demo.cpp:107:58: error: ‘typedef struct SuffixTree::Edge SuffixTree::Edge’ is private within this context
 SuffixTree::Node* SuffixTree::seperate_edge(Node * node, Edge* a_edge)
                                                          ^~~~
In file included from src/suffix_tree_demo.cpp:1:0:
./include/suffix_tree.h:149:22: note: declared private here
  typedef struct Edge Edge;
                      ^~~~
Makefile:257: recipe for target 'suffix_tree_demo' failed
make: *** [suffix_tree_demo] Error 1

**Comment by heshamsafi** [comment]
resolved with #47.

**Comment by xtaci** [comment]
thanks
