### ISSUE TITLE
Conform to C++ standard

### ISSUE THREAD

**Issue by htfy96** [xtaci/algorithms#50]
Hi,
this is an awesome repository which contains a lot of useful algorithms for C++, but the code style, I think, could be improved:
- Use `<cstddef>` instead of `<stddef.h>`
- each identifier with two underscores at the beginning(`__foobar`) or one underscore followed by character in uppercase(`_Foobar`) is [reserved by language](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)
- the `void` keyword could be omitted in`int main(void)`, so is `struct` in `struct Foo obj`

**Comment by xtaci** [comment]
can you provide Pull Requests?

**Comment by htfy96** [comment]
#51
