### ISSUE TITLE
Segregated code

### ISSUE THREAD

**Issue by sonulohani** [xtaci/algorithms#59]
After looking at this project i want to say that this project is good for the one who is learning algorithm. The only opinion i could give right now is that if possible we could segregate the implementations in include directory( only contains the declarations ) and move it to .cpp file( some src directory). It not only helps in readability of the code but also the compile time could increase.

**Comment by matheuspb** [comment]
Actually a lot of the classes are templates and you can't separate implementation and definition of templates.

**Comment by yangjz1125** [comment]
@sonulohani  This project is lightweight. You just need include the head file.
