### ISSUE TITLE
Queue& needs to be const as well

### ISSUE THREAD

**Issue by kounkou** [xtaci/algorithms#83]
https://github.com/xtaci/algorithms/blob/2ac19a715c06f2578c7ebbc201fff6c763320579/include/queue.h#L63

You probably need to make the returned alias to be const as well.
For info, check the (x = y)  = z problem...

**Comment by yangjz1125** [comment]
You are right.But where is the author?

**Comment by kounkou** [comment]
Okay. I will close the issue.
